--- 
- name: Add docker repo
  get_url: 
    url: https://download.docker.com/linux/centos/docker-ce.repo
    dest: /etc/yum.repos.d/docker-ce.repo

- name: Install docker
  package:
    name: [docker-ce-18.09.1-3.el7.x86_64]
    state: present

- name: Create other directories required
  file:
    path: "{{ item }}"
    state: directory
  with_items:
    - /etc/docker
    - /etc/systemd/system/docker.service.d

- name: Set cgroup driver as systemd
  template:
    src: daemon.json.j2
    dest: /etc/docker/daemon.json

- name: Start Docker service
  service:
    name: docker
    state: started
    enabled: yes
    daemon_reload: yes

- name: Add user techuser to docker group
  user:
    name: techuser
    groups: docker
    append: yes

- name: Restart docker service
  systemd:
    name: docker
    state: restarted
    daemon_reload: yes
