---
- name: Add k8s repo
  template:
    src: 'kubernetes.repo.j2'
    dest: /etc/yum.repos.d/kubernetes.repo

- name: Install k8s
  yum:
    name: [kubelet,kubeadm,kubectl]
    disable_excludes: kubernetes

- name: Enable kubelet service
  service:
    name: kubelet
    enabled: yes
