---
- name: Put SELinux in disabled mode
  selinux:
    policy: targeted
    state: disabled

- name: Update system
  package:
    name: "*"
    state: latest

- name: Install common packages
  package:
    name: [vim,bash-completion,wget,curl,yum-utils,lvm2,device-mapper-persistent-data]
    state: present
  ignore_errors: True

- name: Disable swap (1/2)
  shell: |
    swapoff -a

- name : Disable swap infstab (2/2)
  replace:
    path: /etc/fstab
    regexp: '^([^#].*?\sswap\s+.*)$'
    replace: '# \1'

- name: Load required modules
  modprobe:
    name: "{{ item }}"
    state: present
  with_items:
    - br_netfilter
    - overlay
    - ip_vs
    - ip_vs_rr
    - ip_vs_wrr
    - ip_vs_sh
    - nf_conntrack_ipv4

- name: Modify sysctl entries
  sysctl:
    name: '{{ item.key }}'
    value: '{{ item.value }}'
    sysctl_set: yes
    state: present
    reload: yes
  ignore_errors: True
  with_items:
    - {key: net.bridge.bridge-nf-call-ip6tables, value: 1}
    - {key: net.bridge.bridge-nf-call-iptables,  value: 1}
    - {key: net.ipv4.ip_forward,  value: 1}
